# Rotation of NxN Matrix (90 degrees) 

Given an N by N matrix, rotate it by 90 degrees clockwise.

For example, given the following matrix:

```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

you should return:

```
[[7, 4, 1],
 [8, 5, 2],
 [9, 6, 3]]
 ```
Follow-up: What if you couldn't use any extra space?

In [6]:
import numpy as np

In [7]:
A_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [54]:
# This is the brute force way with nested loops (yikes..) 

def rotation_90(matrix): 
    
    # initialize.. 
    N = len(matrix) 
    rotated_Matrix = np.zeros([N,N])
    
    for i in range(N): 
        for j in range(N):
            
            # pretty awkward but N-1-j is used to prevent going out of bounds
            # the loops start from 0 to N-1
            rotated_Matrix[i][j] = matrix[N - 1 - j][i]
    
    return rotated_Matrix

In [55]:
rotation_90(A_matrix)

array([[ 7.,  4.,  1.],
       [ 8.,  5.,  2.],
       [ 9.,  6.,  3.]])

## Alternative syntax

This still will take $O(n^2)$ time and space because of the nested loops

In [58]:
def rotate_matrix(matrix): 
    n = len(matrix) 
    
    # cool way to initialize without using np.zeros([N,N]) 
    new_matrix = [[None for _ in range(n)] for _ in range(n)] 
    
    for r, row in enumerate(matrix): 
        for c, val in enumerate(row): 
            new_matrix[c][n-r-1] = val
            
    return new_matrix

In [57]:
rotate_matrix(A_matrix)

[[7, 4, 1], [8, 5, 2], [9, 6, 3]]

In [60]:
# good visual of the None for _ in range (n) move
# the for _ in range(5) just tells it to ignore the index and just do something
[[None for _ in range(5)] for _ in range(5)]

[[None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None]]

## Clever solution...? perform by performing a chain of four swaps

- top-left with bottom-left
- top-right with top-left
- bottom-right with top-right
- bottom-left with bottom-right

Start with the first row and move down until n // 2, since the bottom rows should be rotated by then.. this still takes $O(n^2)$ time but uses no extra space as everything is rotated in place

In [63]:
def rotate_matrix_CLEVER(matrix): 
    n = len(matrix)
    
    for i in range(n // 2): 
        for j in range(i, n - i - 1): 
            
            # ?? ... not the prettiest 
            p1 = matrix[i][j]
            p2 = matrix[j][n - i - 1] 
            p3 = matrix[n - i  - 1][n - j - 1]
            p4 = matrix[n - j - 1][i] 
            
            matrix[j][n - i - 1] = p1
            matrix[n - i - 1][n - j - 1] = p2
            matrix[n - j - 1][i] = p3
            matrix[i][j] = p4
            
    return matrix

# There's obviously a linear algebra solution here

In [64]:
# there's numpy.rot90? let's try that
np.rot90(A_matrix)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [67]:
np.rot90(A_matrix,k=3) # k specifies number of rotations

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])